/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeighingRouteImport } from './routes/weighing'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as PublicDisplayRouteImport } from './routes/public-display'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as CrushingRouteImport } from './routes/crushing'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ArrivalsRouteImport } from './routes/arrivals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeighingArrivalIdRouteImport } from './routes/weighing.$arrivalId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminScalesRouteImport } from './routes/admin.scales'
import { Route as AdminLinesRouteImport } from './routes/admin.lines'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const WeighingRoute = WeighingRouteImport.update({
  id: '/weighing',
  path: '/weighing',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDisplayRoute = PublicDisplayRouteImport.update({
  id: '/public-display',
  path: '/public-display',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const CrushingRoute = CrushingRouteImport.update({
  id: '/crushing',
  path: '/crushing',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalsRoute = ArrivalsRouteImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeighingArrivalIdRoute = WeighingArrivalIdRouteImport.update({
  id: '/$arrivalId',
  path: '/$arrivalId',
  getParentRoute: () => WeighingRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminScalesRoute = AdminScalesRouteImport.update({
  id: '/admin/scales',
  path: '/admin/scales',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLinesRoute = AdminLinesRouteImport.update({
  id: '/admin/lines',
  path: '/admin/lines',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrivals': typeof ArrivalsRoute
  '/clients': typeof ClientsRoute
  '/crushing': typeof CrushingRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/public-display': typeof PublicDisplayRoute
  '/queue': typeof QueueRoute
  '/stocks': typeof StocksRoute
  '/weighing': typeof WeighingRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/lines': typeof AdminLinesRoute
  '/admin/scales': typeof AdminScalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/weighing/$arrivalId': typeof WeighingArrivalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrivals': typeof ArrivalsRoute
  '/clients': typeof ClientsRoute
  '/crushing': typeof CrushingRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/public-display': typeof PublicDisplayRoute
  '/queue': typeof QueueRoute
  '/stocks': typeof StocksRoute
  '/weighing': typeof WeighingRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/lines': typeof AdminLinesRoute
  '/admin/scales': typeof AdminScalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/weighing/$arrivalId': typeof WeighingArrivalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrivals': typeof ArrivalsRoute
  '/clients': typeof ClientsRoute
  '/crushing': typeof CrushingRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/public-display': typeof PublicDisplayRoute
  '/queue': typeof QueueRoute
  '/stocks': typeof StocksRoute
  '/weighing': typeof WeighingRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/lines': typeof AdminLinesRoute
  '/admin/scales': typeof AdminScalesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/weighing/$arrivalId': typeof WeighingArrivalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrivals'
    | '/clients'
    | '/crushing'
    | '/invoices'
    | '/login'
    | '/production'
    | '/products'
    | '/profile'
    | '/public-display'
    | '/queue'
    | '/stocks'
    | '/weighing'
    | '/admin/audit'
    | '/admin/lines'
    | '/admin/scales'
    | '/admin/settings'
    | '/admin/users'
    | '/weighing/$arrivalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrivals'
    | '/clients'
    | '/crushing'
    | '/invoices'
    | '/login'
    | '/production'
    | '/products'
    | '/profile'
    | '/public-display'
    | '/queue'
    | '/stocks'
    | '/weighing'
    | '/admin/audit'
    | '/admin/lines'
    | '/admin/scales'
    | '/admin/settings'
    | '/admin/users'
    | '/weighing/$arrivalId'
  id:
    | '__root__'
    | '/'
    | '/arrivals'
    | '/clients'
    | '/crushing'
    | '/invoices'
    | '/login'
    | '/production'
    | '/products'
    | '/profile'
    | '/public-display'
    | '/queue'
    | '/stocks'
    | '/weighing'
    | '/admin/audit'
    | '/admin/lines'
    | '/admin/scales'
    | '/admin/settings'
    | '/admin/users'
    | '/weighing/$arrivalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrivalsRoute: typeof ArrivalsRoute
  ClientsRoute: typeof ClientsRoute
  CrushingRoute: typeof CrushingRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  ProductionRoute: typeof ProductionRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PublicDisplayRoute: typeof PublicDisplayRoute
  QueueRoute: typeof QueueRoute
  StocksRoute: typeof StocksRoute
  WeighingRoute: typeof WeighingRouteWithChildren
  AdminAuditRoute: typeof AdminAuditRoute
  AdminLinesRoute: typeof AdminLinesRoute
  AdminScalesRoute: typeof AdminScalesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weighing': {
      id: '/weighing'
      path: '/weighing'
      fullPath: '/weighing'
      preLoaderRoute: typeof WeighingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-display': {
      id: '/public-display'
      path: '/public-display'
      fullPath: '/public-display'
      preLoaderRoute: typeof PublicDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crushing': {
      id: '/crushing'
      path: '/crushing'
      fullPath: '/crushing'
      preLoaderRoute: typeof CrushingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrivals': {
      id: '/arrivals'
      path: '/arrivals'
      fullPath: '/arrivals'
      preLoaderRoute: typeof ArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weighing/$arrivalId': {
      id: '/weighing/$arrivalId'
      path: '/$arrivalId'
      fullPath: '/weighing/$arrivalId'
      preLoaderRoute: typeof WeighingArrivalIdRouteImport
      parentRoute: typeof WeighingRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scales': {
      id: '/admin/scales'
      path: '/admin/scales'
      fullPath: '/admin/scales'
      preLoaderRoute: typeof AdminScalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/lines': {
      id: '/admin/lines'
      path: '/admin/lines'
      fullPath: '/admin/lines'
      preLoaderRoute: typeof AdminLinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WeighingRouteChildren {
  WeighingArrivalIdRoute: typeof WeighingArrivalIdRoute
}

const WeighingRouteChildren: WeighingRouteChildren = {
  WeighingArrivalIdRoute: WeighingArrivalIdRoute,
}

const WeighingRouteWithChildren = WeighingRoute._addFileChildren(
  WeighingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrivalsRoute: ArrivalsRoute,
  ClientsRoute: ClientsRoute,
  CrushingRoute: CrushingRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  ProductionRoute: ProductionRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PublicDisplayRoute: PublicDisplayRoute,
  QueueRoute: QueueRoute,
  StocksRoute: StocksRoute,
  WeighingRoute: WeighingRouteWithChildren,
  AdminAuditRoute: AdminAuditRoute,
  AdminLinesRoute: AdminLinesRoute,
  AdminScalesRoute: AdminScalesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
